reworked files to load on network interface set up, added python3.6 installer

diff --git a/stage2/01-sys-tweaks/files/hq-ui-init b/stage2/01-sys-tweaks/files/hq-ui-init
--- a/stage2/01-sys-tweaks/files/hq-ui-init
+++ b/stage2/01-sys-tweaks/files/hq-ui-init
@@ -1,67 +1,100 @@
-
 #!/bin/sh
 
-
 LOG_FILE="/var/log/hq-ui-install.log"
-GH_TOKEN=${GITHUB_TOKEN}
-GH_USERNAME=${GITHUB_USERNAME}
 
+# Wait limit for connection and retry counts
+WAIT_LIMIT=30
+CONNECTION_RETRY=0
 
-echo "HQapp - Initializing HQ UI Application " >> ${LOG_FILE}
+# Only run if config file has been created
+if [ -f /home/github-config ];
+then
+    echo "HQ | Pre-installation setup... | $(date)" | sudo tee -a ${LOG_FILE}
+	source /home/github-config
+
+    # Check for internet connection. Don't even bother running if not connected.
+    until ping -c 1 www.google.com > /dev/null ; do
+        sleep 1
+        retry=$(($CONNECTION_RETRY+1))
+        if [ $CONNECTION_RETRY -eq $WAIT_LIMIT ]; then
+            echo "[ERR] HQ | Interface not connected and limit reached... | $(date)" | sudo tee -a ${LOG_FILE}
+            exit 0
+        fi
+    done
+else
+    echo "[ERR] HQ | GitHub config file missing. Ensure to create config file before building running pi-gen. | $(date)" | sudo tee -a ${LOG_FILE}
+    exit 0
+fi
+
+echo "HQ | Installing HQ Home UI application... | $(date)" | sudo tee -a ${LOG_FILE}
 sudo apt-get update
 sudo apt-get upgrade -y
 
+# Need to have a reverse proxy installed for us to host our application
+if ! [ -x "$(command -v nginx)" ]; then
+    echo "HQ | Installing web server... | $(date)" | sudo tee -a ${LOG_FILE}
+    sudo apt-get -y install nginx
 
-echo "HQapp - Enabling web server (Nginx) " >> ${LOG_FILE}
-# Ensure nginx is installed
-sudo apt-get install nginx
+    echo "HQ | Enabling firewall... | $(date)" | sudo tee -a ${LOG_FILE}
+    sudo apt-get -y install ufw
+    sudo ufw enable
+fi
 
+# Only run if the repo hasn't been cloned
+if [ ! -d "/home/pi/Documents/hq-home-ui" ]; then
 
-echo "HQapp - Enabling firewall " >> ${LOG_FILE}
-# Enable nginx basic firewall
-sudo apt-get install ufw
-sudo ufw enable
-# restart web server for good measure
-systemctl restart nginx
+    # Need to verify that a github access token was given
+    if [ -z "$GITHUB_USERNAME" ] && [ -z "$GITHUB_PASSWORD" ]
+    then
+        echo "[ERR] HQ | GITHUB_TOKEN was not found. Verify you are setting the config variables correctly. | ${date}" | sudo tee -a ${LOG_FILE}
+        exit 0
+    else
+        echo "HQ | Cloning application... | $(date)" | sudo tee -a ${LOG_FILE}
+        git clone "https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/HQapp/hq-home-ui.git" /home/pi/Documents/hq-home-ui
+    fi
+fi
 
-
-echo "HQapp - Cloning project " >> ${LOG_FILE}
-# This will be where our project sits. Will need this info for continous deployment
-cd "${ROOTFS_DIR}/home/Documents"
-# Need to verify that a github access token was given
-if [ -z "${GITHUB_TOKEN}" ]
+if ! [ -x "$(command -v umi)" ];
 then
-    echo "[ERR] HQapp - GITHUB_TOKEN was not found. Verify you are setting the config variables correctly." >> ${LOG_FILE}
+    echo "HQ | Starting HomeAssistant UI... | $(date)" | sudo tee -a ${LOG_FILE}
+    # Start up HomeAssistant UI
+    sudo hass —open-ui
+
+    echo "HQ - Installing umi.js... | $(date)" | sudo tee -a ${LOG_FILE}
+    # Ensure node/npm is installed
+    if ! [ -x "$(command -v node)" ];
+    then
+        echo "[WARN] HQ - Node.js is not installed. Installing now... | $(date)" | sudo tee -a ${LOG_FILE}
+        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
+        sudo apt-get -y install nodejs
+    fi
+    sudo npm install -g umi
+fi
+
+if [ -d "/home/pi/Documents/hq-home-ui" ]; then
+
+    sudo sh -c 'cd /home/pi/Documents/hq-home-ui && npm install'
+
+    echo "HQ | Deploying application... | $(date)" | sudo tee -a ${LOG_FILE}
+    # Build the application and copy its contents to /www/html/ so we can
+    # enable port forwarding from Dataplicity
+    sudo sh -c 'cd /home/pi/Documents/hq-home-ui && npm run build'
+    sudo sh -c 'rm -rf /var/www/html/*'
+    sudo sh -c 'cp -a /home/pi/Documents/hq-home-ui/dist/. /var/www/html/'
+
+    echo "HQ | Finishing up deployment... | $(date)" | sudo tee -a ${LOG_FILE}
+    # Restart the web server
+    sudo systemctl restart nginx
+
+    # Cleaning up installation files
+    /bin/sh -c "sudo rm /home/hq-ui-init /home/github-config"
+
+    echo "HQ | HQ Home UI installation complete | $(date)" | sudo tee -a ${LOG_FILE}
+    exit 0
 else
-    git clone "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/HQapp/hq-home-ui.git"
+    echo "HQ | Repository not cloned or does not exist... | $(date)" | sudo tee -a ${LOG_FILE}
+    exit 0
 fi
-
-
-echo "Initializing Umi " >> ${LOG_FILE}
-# Ensure node/npm is installed
-if ! [ -x "${command -v node}" ]; then
-    echo "[WARN] HQapp - Node is not installed. Installing now " >> $LOG_FILE
-    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
-    sudo apt-get install nodejs npm
-fi
-sudo npm i -g umi
-
-echo "Building and deploying HQ's UI" >> ${LOG_FILE}
-# Build the application and copy its contents to /www/html so we can
-# enable wormhole tunneling from Dataplicity (remote connection)
-# to the application
-umi build
-cp -a ~/hq-home-ui/dist/. /var/www/html/
-
-echo "Restarting web server to finish deployment..." >> ${LOG_FILE}
-systemctl restart nginx
-
-echo "HQapp - Initialization complete" >> ${LOG_FILE}
-
-rm /boot/rpi_init
-
-source /etc/rc.local
-exit 0
 
 
 
